use std::collections::BTreeSet;
use std::process::Command;

use sha2::{Digest, Sha256};
use tracing::warn;

/// Get git root directory
fn get_git_root() -> Option<String> {
    let output = Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .ok()?;

    if output.status.success() {
        let result = String::from_utf8(output.stdout).ok()?;
        Some(result.trim_end_matches(['\r', '\n']).to_string())
    } else {
        None
    }
}

/// Get the preferred Unix socket directory.
/// Prefers XDG_RUNTIME_DIR, then TMPDIR, falls back to /tmp.
#[cfg(unix)]
fn get_socket_dir() -> String {
    if let Ok(xdg) = std::env::var("XDG_RUNTIME_DIR")
        && !xdg.is_empty()
    {
        return xdg;
    }
    if let Ok(tmpdir) = std::env::var("TMPDIR")
        && !tmpdir.is_empty()
    {
        return tmpdir;
    }
    "/tmp".to_string()
}

/// Get all directories to search for sockets.
/// Includes both the preferred dir and /tmp as legacy fallback, deduplicated.
#[cfg(unix)]
fn get_socket_search_dirs() -> BTreeSet<String> {
    BTreeSet::from([get_socket_dir(), "/tmp".to_string()])
}

/// Find all existing nvim-mcp socket targets in the filesystem
/// Returns a vector of socket paths that match the pattern generated by the Lua plugin
#[cfg(unix)]
pub fn find_get_all_targets() -> Vec<String> {
    let mut targets = Vec::new();
    for dir in get_socket_search_dirs() {
        let pattern = format!("{}/nvim-mcp.*.sock", glob::Pattern::escape(&dir));
        if let Ok(paths) = glob::glob(&pattern) {
            targets.extend(
                paths
                    .filter_map(|entry| entry.ok())
                    .map(|path| path.to_string_lossy().to_string()),
            );
        }
    }
    targets
}

/// Get current project root directory
/// Tries git root first, falls back to current working directory
pub(super) fn get_current_project_root() -> String {
    // Try git root first
    if let Some(git_root) = get_git_root() {
        return git_root;
    }

    // Fallback to current working directory
    std::env::current_dir()
        .unwrap_or_else(|err| {
            warn!("Failed to get current working directory: {}", err);
            std::path::PathBuf::from("<unknown project root>")
        })
        .to_string_lossy()
        .to_string()
}

/// Match the escaped project paths used by older Unix plugins.
#[cfg(unix)]
fn escape_path(path: &str) -> String {
    path.trim().replace("/", "%")
}

/// Matches the first 64 bits of vim.fn.sha256 in the Lua plugin.
fn project_socket_id(project_root: &str) -> String {
    #[cfg(windows)]
    let project_root = {
        let path = std::fs::canonicalize(project_root)
            .unwrap_or_else(|_| std::path::PathBuf::from(project_root));
        normalize_windows_project_path(&path.to_string_lossy())
    };
    format!("{:x}", Sha256::digest(project_root.as_bytes()))[..16].to_string()
}

/// Find both current and legacy socket names during plugin upgrades.
#[cfg(unix)]
fn find_project_targets(project_root: &str, dirs: BTreeSet<String>) -> Vec<String> {
    let project_ids = [project_socket_id(project_root), escape_path(project_root)];
    let mut targets = BTreeSet::new();
    for dir in dirs {
        for project_id in &project_ids {
            let pattern = format!(
                "{}/nvim-mcp.{}.*.sock",
                glob::Pattern::escape(&dir),
                glob::Pattern::escape(project_id),
            );
            match glob::glob(&pattern) {
                Ok(paths) => {
                    targets.extend(
                        paths
                            .filter_map(|entry| entry.ok())
                            .map(|path| path.to_string_lossy().to_string()),
                    );
                }
                Err(e) => {
                    warn!(
                        "Glob error while searching for Neovim sockets with pattern '{}': {}",
                        pattern, e
                    );
                }
            }
        }
    }
    targets.into_iter().collect()
}

/// Find nvim-mcp socket targets for the current project only.
#[cfg(unix)]
pub fn find_targets_for_current_project() -> Vec<String> {
    find_project_targets(&get_current_project_root(), get_socket_search_dirs())
}

#[cfg(any(windows, test))]
fn normalize_windows_project_path(path: &str) -> String {
    let path = path.replace('\\', "/");
    let mut path = if let Some(unc) = path.strip_prefix("//?/UNC/") {
        format!("//{unc}")
    } else {
        path.strip_prefix("//?/").unwrap_or(&path).to_string()
    };
    if path.as_bytes().get(1) == Some(&b':') {
        path[..1].make_ascii_lowercase();
    }
    path.trim_end_matches('/').to_string()
}

#[cfg(any(windows, test))]
fn matching_pipe_target(name: &str, project_id: Option<&str>) -> Option<String> {
    let (id, pid) = name
        .strip_prefix("nvim-mcp.")?
        .strip_suffix(".sock")?
        .split_once('.')?;
    if id.len() != 16
        || !id.bytes().all(|byte| byte.is_ascii_hexdigit())
        || pid.is_empty()
        || !pid.bytes().all(|byte| byte.is_ascii_digit())
        || pid.parse::<u32>().ok()? == 0
        || project_id.is_some_and(|project_id| !id.eq_ignore_ascii_case(project_id))
    {
        return None;
    }
    Some(format!(r"\\.\pipe\{name}"))
}

#[cfg(windows)]
fn find_pipe_targets(project_id: Option<&str>) -> Vec<String> {
    use windows_sys::Win32::{
        Foundation::{ERROR_FILE_NOT_FOUND, ERROR_NO_MORE_FILES, HANDLE, INVALID_HANDLE_VALUE},
        Storage::FileSystem::{FindClose, FindFirstFileW, FindNextFileW, WIN32_FIND_DATAW},
    };

    struct SearchHandle(HANDLE);
    impl Drop for SearchHandle {
        fn drop(&mut self) {
            // SAFETY: This handle comes from FindFirstFileW and is closed exactly once.
            unsafe { FindClose(self.0) };
        }
    }

    let mut data = WIN32_FIND_DATAW::default();
    // Enumerate the pipe namespace directly; filesystem globbing checks directory metadata.
    // SAFETY: The pattern is NUL-terminated and data is valid writable storage.
    let handle = unsafe { FindFirstFileW(windows_sys::w!(r"\\.\pipe\*"), &mut data) };
    if handle == INVALID_HANDLE_VALUE {
        let error = std::io::Error::last_os_error();
        if error.raw_os_error() != Some(ERROR_FILE_NOT_FOUND as i32) {
            warn!("Failed to enumerate Neovim named pipes: {error}");
        }
        return Vec::new();
    }
    let handle = SearchHandle(handle);
    let mut targets = BTreeSet::new();
    loop {
        let length = data
            .cFileName
            .iter()
            .position(|&unit| unit == 0)
            .unwrap_or(data.cFileName.len());
        if let Ok(name) = String::from_utf16(&data.cFileName[..length])
            && let Some(target) = matching_pipe_target(&name, project_id)
        {
            targets.insert(target);
        }
        // SAFETY: The search handle is live and data remains valid writable storage.
        if unsafe { FindNextFileW(handle.0, &mut data) } == 0 {
            let error = std::io::Error::last_os_error();
            if error.raw_os_error() != Some(ERROR_NO_MORE_FILES as i32) {
                warn!("Failed to continue enumerating Neovim named pipes: {error}");
            }
            break;
        }
    }
    targets.into_iter().collect()
}

#[cfg(windows)]
pub fn find_get_all_targets() -> Vec<String> {
    find_pipe_targets(None)
}

#[cfg(windows)]
pub fn find_targets_for_current_project() -> Vec<String> {
    find_pipe_targets(Some(&project_socket_id(&get_current_project_root())))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn windows_project_paths_normalize_drive_separators_and_verbatim_prefixes() {
        for path in [
            r"C:\dev\Project Name\",
            "C:/dev/Project Name",
            r"\\?\c:\dev\Project Name",
        ] {
            assert_eq!(normalize_windows_project_path(path), "c:/dev/Project Name");
        }
        for path in [r"\\server\share\Project\", r"\\?\UNC\server\share\Project"] {
            assert_eq!(
                normalize_windows_project_path(path),
                "//server/share/Project"
            );
        }
        assert_eq!(normalize_windows_project_path(r"C:\"), "c:");
    }

    #[test]
    fn pipe_names_match_only_plugin_instances_and_the_requested_project() {
        let id = "0123456789abcdef";
        let name = format!("nvim-mcp.{id}.123.sock");
        let expected = Some(format!(r"\\.\pipe\{name}"));
        assert_eq!(matching_pipe_target(&name, None), expected);
        assert_eq!(matching_pipe_target(&name, Some(id)), expected);
        assert_eq!(matching_pipe_target(&name, Some("fedcba9876543210")), None);
        for name in [
            "nvim.123.0",
            "nvim-mcp.short.123.sock",
            "nvim-mcp.0123456789abcdeg.123.sock",
            "nvim-mcp.0123456789abcdef.0.sock",
            "nvim-mcp.0123456789abcdef..sock",
            "nvim-mcp.0123456789abcdef.123.sock.extra",
            "nvim-mcp.0123456789abcdef.4294967296.sock",
        ] {
            assert_eq!(
                matching_pipe_target(name, None),
                None,
                "Unexpected match: {name}"
            );
        }
    }

    #[cfg(windows)]
    #[tokio::test]
    async fn named_pipe_enumeration_filters_projects_and_removes_closed_instances() {
        use tokio::net::windows::named_pipe::ServerOptions;

        let project = crate::test_utils::generate_random_id();
        let id = project_socket_id(&project);
        let other_id = project_socket_id(&format!("{project}-other"));
        let first = format!(r"\\.\pipe\nvim-mcp.{id}.123.sock");
        let second = format!(r"\\.\pipe\nvim-mcp.{id}.456.sock");
        let other = format!(r"\\.\pipe\nvim-mcp.{other_id}.789.sock");
        let servers: Vec<_> = [&first, &second, &other]
            .into_iter()
            .map(|path| {
                ServerOptions::new()
                    .first_pipe_instance(true)
                    .create(path)
                    .unwrap()
            })
            .collect();
        let targets = find_get_all_targets();
        for target in [&first, &second, &other] {
            assert!(targets.contains(target), "Missing named pipe: {target}");
        }
        assert_eq!(find_pipe_targets(Some(&id)), vec![first, second]);
        drop(servers);
        assert!(find_pipe_targets(Some(&id)).is_empty());
    }

    #[tokio::test]
    async fn integration_tests_plugin_discovery() -> Result<(), Box<dyn std::error::Error>> {
        use crate::neovim::{NeovimClient, NeovimClientTrait};
        use crate::test_utils::{NeovimIpcGuard, get_compiled_binary};
        use rmcp::{ServiceExt, model::CallToolRequestParams, transport::TokioChildProcess};
        use std::time::Duration;

        let temp = tempfile::tempdir()?;
        #[cfg(unix)]
        let runtime = tempfile::Builder::new()
            .prefix("nvim-mcp-")
            .tempdir_in("/tmp")?;
        #[cfg(windows)]
        let runtime = tempfile::tempdir()?;

        for in_git in [false, true] {
            let project = temp
                .path()
                .join(format!("project [1] \u{4e2d}\u{6587} {in_git}"));
            let other = temp.path().join(format!("other {in_git}"));
            std::fs::create_dir(&project)?;
            std::fs::create_dir(&other)?;
            let cwd = if in_git {
                let output = Command::new("git")
                    .args(["init", "--quiet"])
                    .arg(&project)
                    .env_remove("GIT_DIR")
                    .env_remove("GIT_WORK_TREE")
                    .output()?;
                assert!(
                    output.status.success(),
                    "{}",
                    String::from_utf8_lossy(&output.stderr)
                );
                let nested = project.join("nested");
                std::fs::create_dir(&nested)?;
                nested
            } else {
                project.clone()
            };
            let mut guards = Vec::new();
            let mut targets = Vec::new();
            for (root, directory) in [(&project, &cwd), (&project, &cwd), (&other, &other)] {
                let root = root.canonicalize()?;
                let child = Command::new("nvim")
                    .args(["--headless", "-i", "NONE", "-n", "-u"])
                    .arg(concat!(
                        env!("CARGO_MANIFEST_DIR"),
                        "/src/testdata/cfg_discovery.lua"
                    ))
                    .current_dir(directory)
                    .env_remove("GIT_DIR")
                    .env_remove("GIT_WORK_TREE")
                    .env("NVIM_MCP_ROOT", env!("CARGO_MANIFEST_DIR"))
                    .env("XDG_RUNTIME_DIR", runtime.path())
                    .stdin(std::process::Stdio::null())
                    .spawn()?;
                let filename = format!(
                    "nvim-mcp.{}.{}.sock",
                    project_socket_id(root.to_str().unwrap()),
                    child.id()
                );
                #[cfg(unix)]
                let target = runtime.path().join(filename).to_string_lossy().into_owned();
                #[cfg(windows)]
                let target = format!(r"\\.\pipe\{filename}");
                guards.push(NeovimIpcGuard::new(child, target.clone()));
                let mut client = NeovimClient::default();
                tokio::time::timeout(Duration::from_secs(15), async {
                    loop {
                        if client.connect_path(&target).await.is_ok() {
                            break;
                        }
                        tokio::time::sleep(Duration::from_millis(50)).await;
                    }
                })
                .await?;
                client.get_buffers().await?;
                client.disconnect().await?;
                targets.push(target);
            }

            let mut command = tokio::process::Command::new(get_compiled_binary());
            command
                .args(["--connect", "auto", "--always-expose-connection-tools"])
                .current_dir(&cwd)
                .env_remove("GIT_DIR")
                .env_remove("GIT_WORK_TREE")
                .env("XDG_RUNTIME_DIR", runtime.path());
            let service = tokio::time::timeout(
                Duration::from_secs(15),
                ().serve(TokioChildProcess::new(command)?),
            )
            .await??;
            let discovered = service
                .call_tool(CallToolRequestParams::new("get_targets"))
                .await?;
            let text = &discovered.content[0].as_text().unwrap().text;
            let discovered: Vec<String> = serde_json::from_str(text)?;
            for target in &targets {
                assert!(
                    discovered.contains(target),
                    "Missing plugin target: {target}"
                );
            }
            for (index, target) in targets.iter().enumerate() {
                let id = &crate::server::core::b3sum(target)[..7];
                let result = service
                    .call_tool(CallToolRequestParams::new("list_buffers").with_arguments(
                        serde_json::from_value(serde_json::json!({"connection_id": id}))?,
                    ))
                    .await;
                if index < 2 {
                    assert!(
                        !result?.is_error.unwrap_or(false),
                        "Failed to use auto-connected instance"
                    );
                } else {
                    let error = result.expect_err("Connected to another project");
                    assert!(error.to_string().contains("No Neovim connection found"));
                }
            }
            service.cancel().await?;
            drop(guards);
        }
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn discovery_matches_hashed_and_legacy_names_literally() {
        let temp = tempfile::tempdir().unwrap();
        let dir = temp.path().join("runtime[1]");
        std::fs::create_dir(&dir).unwrap();
        let project = "/workspace/project[1]";
        let expected: BTreeSet<String> = [project_socket_id(project), escape_path(project)]
            .into_iter()
            .map(|id| {
                let path = dir.join(format!("nvim-mcp.{id}.123.sock"));
                std::fs::write(&path, "").unwrap();
                path.to_str().unwrap().to_string()
            })
            .collect();
        for other in ["/workspace/project1", "/workspace/other"] {
            for id in [project_socket_id(other), escape_path(other)] {
                std::fs::write(dir.join(format!("nvim-mcp.{id}.123.sock")), "").unwrap();
            }
        }
        assert_eq!(
            find_project_targets(project, BTreeSet::from([dir.to_str().unwrap().to_string()])),
            expected.into_iter().collect::<Vec<_>>()
        );
    }

    #[cfg(unix)]
    #[test]
    fn integration_tests_lua_socket_paths() {
        let temp = tempfile::tempdir().unwrap();
        let project = temp.path().join("long-project-".repeat(12));
        std::fs::create_dir(&project).unwrap();
        let runtime = tempfile::Builder::new()
            .prefix("nvim-mcp-")
            .tempdir_in("/tmp")
            .unwrap();
        // Match the length of a typical macOS /var/folders temporary directory.
        let mac_runtime = runtime
            .path()
            .join("r".repeat(48 - runtime.path().as_os_str().len() - 1));
        std::fs::create_dir(&mac_runtime).unwrap();
        let project = project.canonicalize().unwrap();
        let project_id = project_socket_id(project.to_str().unwrap());
        for in_git in [false, true] {
            let cwd = if in_git {
                let output = Command::new("git")
                    .args(["init", "--quiet"])
                    .arg(&project)
                    .output()
                    .unwrap();
                assert!(output.status.success());
                let nested = project.join("nested");
                std::fs::create_dir(&nested).unwrap();
                nested
            } else {
                project.clone()
            };
            for (xdg, tmp, expected_dir) in [
                (runtime.path(), mac_runtime.as_path(), runtime.path()),
                (
                    std::path::Path::new(""),
                    mac_runtime.as_path(),
                    mac_runtime.as_path(),
                ),
                (mac_runtime.as_path(), runtime.path(), mac_runtime.as_path()),
                (
                    std::path::Path::new(""),
                    std::path::Path::new(""),
                    std::path::Path::new("/tmp"),
                ),
            ] {
                let output = Command::new("nvim")
                    .args(["--headless", "-u", "NONE", "-i", "NONE", "-n", "-l"])
                    .arg(concat!(
                        env!("CARGO_MANIFEST_DIR"),
                        "/src/testdata/socket_paths.lua"
                    ))
                    .current_dir(&cwd)
                    .env_remove("GIT_DIR")
                    .env_remove("GIT_WORK_TREE")
                    .env("XDG_RUNTIME_DIR", xdg)
                    .env("TMPDIR", tmp)
                    .env("NVIM_MCP_ROOT", env!("CARGO_MANIFEST_DIR"))
                    .env("NVIM_MCP_EXPECTED_ID", &project_id)
                    .env("NVIM_MCP_EXPECTED_DIR", expected_dir)
                    .output()
                    .unwrap();
                assert!(
                    output.status.success(),
                    "{}",
                    String::from_utf8_lossy(&output.stderr)
                );
            }
        }
    }
}
