[package]
name = "nvim-mcp"
version = "0.1.0"
edition = "2024"
description = "MCP server for Neovim"
license = "MIT"

[dependencies]
# Async Runtime and Concurrency
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }

# Error Handling
thiserror = "2.0"

# Logging and Tracing
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-appender = "0.2"

# CLI Argument Parsing
clap = { version = "4.5", features = ["derive"] }

# MCP Protocol Implementation
rmcp = { version = "0.3.0", features = [
  "transport-io",
  "transport-child-process",
  "client",
] }

# Neovim Integration
nvim-rs = { version = "0.9.2", features = ["use_tokio"] }
rmpv = "1.0"

# Serialization
serde = "1.0.219"
serde_json = "1.0.141"

[dev-dependencies]
tracing-test = "0.2"
