name: "CD"
on:
  push:
    tags:
      - "v*"

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Build binary
        run: nix build

  publish:
    needs:
      - build-binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Publish crates.io
        run: |
          nix develop --command cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
