name: "CD"
on:
  push:
    tags:
      - "v*"

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-nix

      - name: Build binary
        run: nix build --profile default
      # use --profile default to avoid dependencies being gc

  publish:
    needs:
      - nix-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-nix

      - name: Bake commit SHA into crate
        run: echo "${GITHUB_SHA}" > .packaged-commit

      - name: Publish crates.io
        run: |
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }} --allow-dirty
